# Generated by Django 5.2.15 on 2026-06-10 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_language', models.CharField(blank=True, max_length=100)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='profiles.profile')),
                ('subjects', models.ManyToManyField(blank=True, to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_org', models.CharField(blank=True, max_length=200)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='certificates/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='teachers.teacherprofile')),
            ],
        ),
    ]
