# Generated by Django 5.2.15 on 2026-06-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_mode',
            field=models.CharField(choices=[('online', 'Online'), ('presential', 'Presential'), ('both', 'Both')], default='both', max_length=20),
        ),
    ]
