# Generated by Django 5.2.15 on 2026-07-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_teaching_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
