# Generated by Django 5.2.15 on 2026-07-06 17:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_populate_languages"),
        ("teachers", "0003_availability_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teaching_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("presential", "Presential"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("individual", "Individual lesson"),
                            ("group", "Group / Conversation table"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("all", "All levels"),
                            ("beginner", "Beginner"),
                            ("elementary", "Elementary"),
                            ("intermediate", "Intermediate"),
                            ("upper_intermediate", "Upper-intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="teachers.teacherprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["subject__name", "format"],
            },
        ),
    ]
