# Generated by Django 5.2.15 on 2026-08-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_class_offering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='native_language',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
    ]
