# Generated by Django 5.2.15 on 2026-08-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_remove_native_language_and_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classoffering',
            name='format',
            field=models.CharField(choices=[('individual', 'Individual lesson'), ('group', 'Group')], default='individual', max_length=20),
        ),
    ]
