# Generated by Django 5.2.15 on 2026-08-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_classoffering_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teaching_mode',
        ),
    ]
