# Generated by Django 5.2.15 on 2026-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(blank=True, choices=[('languages', 'Languages'), ('sciences', 'Sciences'), ('humanities', 'Humanities'), ('arts', 'Arts'), ('sports', 'Sports'), ('professional', 'Professional skills')], default='languages', max_length=50),
        ),
    ]
